CREATE TABLE IF NOT EXISTS public.animal_exam_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    source_file_name TEXT,
    extracted_values JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.animal_exam_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own exam history"
ON public.animal_exam_history
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users insert own exam history"
ON public.animal_exam_history
FOR INSERT
WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
        SELECT 1
        FROM public.animals a
        WHERE a.id = animal_id
          AND a.user_id = auth.uid()
    )
);

CREATE POLICY "Users delete own exam history"
ON public.animal_exam_history
FOR DELETE
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS animal_exam_history_animal_id_idx
ON public.animal_exam_history (animal_id, created_at DESC);
